#!/usr/bin/env python3
"""Hook tarefas: task rows on the Notion daily page, through the SHARED engine watch_core.tasks.

This hook only says what is the instance's: the code (sigla, ids <SIGLA>-N), the first date the engine owns the page,
the page labels (pt | en), how a text becomes a link (PR and issue references), how to fix each broken source (each
source's "conserto") and the extra rows (each source's tarefas_extras). Live instances only (it writes to Notion).

Config ("ganchos": [{"tipo": "tarefas", ...}]):
  inicio      "YYYY-MM-DD": first page generated by the engine
  rotulos     "pt" | "en" (default: the instance "idioma_pagina")
  links       {"repo_regex": "<regex of repo names>", "pr_url": "https://.../{repo}/pull/{n}",
               "issue_url": "https://.../browse/{key}"}
  passos      engine steps in order (default: verifica, verifica_links, tick, duplicadas, cobrancas, top_cobra, sem_tarefa)
  modulo      an instance adapter (~/.config/work-watch/<instance>/adapters/<name>.py) with `ganchos(ctx) -> dict` of extra
              engine hooks (link_auto, autolink, necessidades, verifica_links, sem_tarefa_fontes, verifica_cwd, conserto...)
              that override the ones built from "links"; company-only rules (what the watcher needs from the user, how a
              task closes by itself) live there

Test mode (not live): it does not run.
"""
import re
from datetime import datetime, timezone

import core, paths
from adapters import Gancho as Base

PASSOS = ('verifica', 'verifica_links', 'tick', 'duplicadas', 'cobrancas', 'top_cobra', 'sem_tarefa')


def aplica(s, cod, status):
    """Box ticked on the page: action done / pending item resolved. PRs and issues close at the source."""
    from watch_core import daily as dvm
    if cod.startswith('a') and cod[1:].isdigit():
        return bool(dvm.acao_done(s, int(cod[1:]), 'marcada no Notion')) if status == 'Feito' else False
    p = next((p for p in s.get('pendencias') or [] if p['chave'] == cod and p.get('status') == 'aberta'), None)
    if not p: return False
    if status == 'Feito':
        p['status'] = 'resolvida'; p['resolvida'] = datetime.now(timezone.utc).isoformat(); p['como'] = 'marcada no Notion'
    else:
        p['status'] = 'ignorar'; p['nota'] = 'descartada no Notion'
    return True


class Gancho(Base):
    tipo = 'tarefas'
    tc = None
    atribui = True                                  # --top may number the tasks that have no <SIGLA>-N yet

    def _configura_core(self, ctx):
        if self.tc: return self.tc
        from watch_core import tasks as tc
        lk = self.cfg.get('links') or {}
        repo_re, pr_url, issue_url = lk.get('repo_regex'), lk.get('pr_url'), lk.get('issue_url')

        def link_auto(texto):
            # PLN0256: a text that waits on a merge ("when A merges, do B") or cites several PRs is not the task of one PR:
            # no PR link, so a link-state closer never ties it to the first PR cited
            if repo_re and pr_url and not tc.condicional(texto) and len(tc.pr_refs(texto)) < 2:
                m = re.search(rf'\b({repo_re})\s?#(\d+)', texto or '')     # PR first
                if m: return pr_url.format(repo=m.group(1), n=m.group(2))
            m = re.search(r'\b([A-Z][A-Z0-9]+-\d+)\b', texto or '')
            return issue_url.format(key=m.group(1)) if (m and issue_url) else ''

        def autolink(t):
            if issue_url:
                t = re.sub(r'(?<![\[\w/-])([A-Z][A-Z0-9]+-\d+)\b', lambda m: f'[{m.group(1)}]({issue_url.format(key=m.group(1))})', t)
            if repo_re and pr_url:
                t = re.sub(rf'(?<![\[\w/])({repo_re}) ?#(\d+)',
                           lambda m: f'[{m.group(1)} #{m.group(2)}]({pr_url.format(repo=m.group(1), n=m.group(2))})', t)
            return t

        fontes = list(ctx.fontes.values())

        def extras(s, agora):
            agora = agora or datetime.now(timezone.utc)
            out = {}
            for f in fontes: out.update(f.tarefas_extras(s, agora) or {})
            return out

        conserto = {f.nome: f.conserto for f in fontes if f.conserto}
        rot = (self.cfg.get('rotulos') or ctx.cfg.get('idioma_pagina') or 'pt').lower()
        g = dict(link_auto=link_auto, autolink=autolink, conserto=conserto, fontes_extras=extras,
                 inicio=self.cfg.get('inicio'), rotulos=tc.ROT_EN if rot == 'en' else tc.ROT_PT)
        if any(e.get('tipo') == 'custos' for e in ctx.cfg.get('ganchos') or []):
            from adapters import carrega
            cu, en = carrega('custos'), rot == 'en'
            usd = any(e.get('tipo') == 'custos' and e.get('unidade') == 'usd' for e in ctx.cfg.get('ganchos') or [])
            g.update(extra_linha=lambda s, it: cu.extra_linha(s, it['uid'], en, usd), rodape=lambda s, data: cu.rodape(s, data, en, usd))
        if self.cfg.get('modulo'):
            from adapters import carrega
            g.update(carrega(self.cfg['modulo']).ganchos(ctx) or {})
        tc.configura(ctx.cfg.get('sigla'), **g)
        self.tc = tc
        return tc

    def args(self, ap):
        ap.add_argument('--top', nargs='+', metavar='SIGLA-N',
                        help='Top do dia: marca ate 3 tarefas (na ordem) como o que faz o dia valer; "--top -" limpa o de hoje')

    def cli(self, a, ctx):
        """--top AUR-1 AUR-7 (up to 3, in order) | --top - (today on purpose without a top). Same state key the engine's
        own CLI writes (tarefas_notion.top[<today BRT>]); the page picks it up on the next tick."""
        if a.top is None: return False
        core.exige_live('--top')
        tc = self._configura_core(ctx)
        s = ctx.s
        m = tc.ids(s) if self.atribui else tc.ids_gravados(s)   # with the hook, the <SIGLA>-N of a fresh instance are born here
        arg = a.top[:3]
        if arg != ['-']:
            cods = [tc.interno(s, x) for x in arg]
            ruins = [x for x, c in zip(arg, cods) if c not in m]
            if ruins: raise SystemExit(f'--top: tarefa desconhecida: {", ".join(ruins)} (use o {tc.SIGLA}-N da pagina do dia)')
        tt = s.setdefault('tarefas_notion', {}).setdefault('top', {})
        hoje = datetime.now(tc.BRT).date().isoformat()
        for k in [k for k in tt if k < hoje]: tt.pop(k)
        tt[hoje] = [] if arg == ['-'] else cods
        core.save_state(s)
        print('top de hoje ->', [m.get(c, c) for c in tt[hoje]] or '(vazio)')
        return True

    def publica(self, ctx, blocos):
        if not core.LIVE: return []
        s, dry = ctx.s, ctx.dry
        try:
            tc = self._configura_core(ctx)
            linhas = []
            for passo in self.cfg.get('passos') or PASSOS:
                fn = getattr(tc, passo)
                linhas += fn(s, dry, lambda c, st: aplica(s, c, st)) if passo == 'tick' else fn(s, dry)
            return ['\n'.join(['== TAREFAS (Notion)'] + linhas)] if linhas else []
        except core.Teste: raise
        except Exception as e:
            ctx.quebrados.append(('tarefas', f'{type(e).__name__}: {e}'))
            return []


class SoTop(Gancho):
    """Only --top, for an instance with a "code" whose tasks engine runs inside its own adapter (no "tarefas" hook):
    agent.py adds it when nothing else registered --top. It never publishes nor runs an engine step (the instance
    adapter does that) and it never numbers tasks: the engine is configured with the code alone, without the
    instance's extra rows, so it only accepts the <SIGLA>-N the page already shows (tarefas_notion.ids)."""
    tipo = None
    atribui = False

    def _configura_core(self, ctx):
        from watch_core import tasks as tc
        if tc.SIGLA is None: tc.configura(ctx.cfg.get('code'))
        self.tc = tc
        return tc

    def publica(self, ctx, blocos): return []
